version: '3.8'

services:
 wordpress:
  build:
    context: ./requirements/wordpress
    dockerfile: Dockerfile
  image: wordpress
  volumes:
    - /home/dgarizad/data/wpsite:/var/www/html
  restart: always
  expose:
    -  9000
  env_file: .env
  depends_on: 
    -  mariadb
  container_name: wpcontainer
  networks:
    -  inceptionnet

 mariadb:
    build:
      context: ./requirements/mariaDB/
      dockerfile: Dockerfile
    image: mariadb
    restart: always
    expose:
     - 3306
    env_file: .env
    volumes:
      - mariadb-data:/var/lib/mysql
    container_name: dbcontainer
    networks:
      - inceptionnet

 nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx
    restart: always
    env_file: .env
    volumes:
    - /home/dgarizad/data/wpsite:/var/www/html
    ports:
      - "443:443"
    depends_on:
      - wordpress
    container_name: ngxcontainer
    networks:
      - inceptionnet

 #BONUS:
 redis:
    build:
      context: ./requirements/bonus/redis
      dockerfile: Dockerfile
    image: redis
    restart: always
    env_file: .env
    container_name: rediscontainer
    networks:
      - inceptionnet

 ftp:
    build:
      context: ./requirements/bonus/ftp
      dockerfile: Dockerfile
    image: ftp
    restart: always
    # depends_on:
    #   - wordpress
    env_file: .env
    volumes:
    - /home/dgarizad/data/wpsite:/home/dgarizad/ftp
    ports:
     - "21:21"
     - "21000:21000"
    container_name: ftpcontainer
    networks:
      - inceptionnet

 adminer:
    build:
      context: ./requirements/bonus/adminer
      dockerfile: Dockerfile
    image: adminer
    restart: always
    depends_on:
      - mariadb
    env_file: .env
    ports:
     - "600:80"
    container_name: admcontainer
    networks:
      - inceptionnet

 static:
    build:
      context: ./requirements/bonus/static
      dockerfile: Dockerfile
    image: static
    restart: always
    depends_on:
      - mariadb
    env_file: .env
    ports:
     - "3000:3000"
    container_name: statcontainer
    networks:
      - inceptionnet

 extra:
    build:
      context: ./requirements/bonus/extra
      dockerfile: Dockerfile
    image: extra
    restart: always
    depends_on:
      - mariadb
    env_file: .env
    ports:
     - "8080:8080"
    container_name: xtrcontainer
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro 
      - /sys:/sys:ro 
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - inceptionnet


volumes:
  wordpress:
   driver: local
   driver_opts:
           device: /home/dgarizad/data/wpsite
           o: bind
           type: none
  mariadb-data:
   driver: local
   driver_opts:
           device: /home/dgarizad/data/database
           o: bind
           type: none

networks:
  inceptionnet:
    driver: bridge
