
version: '3.8'

services:
 wordpress:
  build:
    context: ./requirements/wordpress
    dockerfile: Dockerfile
  image: wpimage:latest
  volumes:
    - /home/dgarizad/data/wpsite:/var/www/html
  restart: always
  expose:
    -  9000
  env_file: .env
  depends_on: 
    -  mariadb
    # -  redis
  container_name: wpcontainer
  networks:
    -  inceptionnet

 mariadb:
    build:
      context: ./requirements/mariaDB/
      dockerfile: Dockerfile
    image: dbimage
    restart: always
    env_file: .env
    volumes:
      - mariadb-data:/var/lib/mysql
    container_name: dbcontainer
    networks:
      - inceptionnet

 nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: ngximage:latest
    restart: always
    env_file: .env
    volumes:
    - /home/dgarizad/data/wpsite:/var/www/html
    ports:
      - "443:443"
    depends_on:
      - wordpress
    container_name: ngxcontainer
    networks:
      - inceptionnet

 redis:
    build:
      context: ./requirements/bonus/redis
      dockerfile: Dockerfile
    image: redisimage:latest
    restart: always
    env_file: .env
    container_name: rediscontainer
    networks:
      - inceptionnet

 ftp:
    build:
      context: ./requirements/bonus/ftp
      dockerfile: Dockerfile
    image: ftpimage:latest
    restart: always
    # depends_on:
    #   - wordpress
    env_file: .env
    volumes:
    - /home/dgarizad/data/wpsite:/home/dgarizad/ftp
    ports:
     - "21:21"
     - "21100-21110:21100-21110"
    container_name: ftpcontainer
    networks:
      - inceptionnet

 adminer:
    build:
      context: ./requirements/bonus/adminer
      dockerfile: Dockerfile
    image: admimage:latest
    restart: always
    depends_on:
      - mariadb
    env_file: .env
    ports:
     - "600:80"
    container_name: admcontainer
    networks:
      - inceptionnet
      
volumes:
  # wpdata:
  mariadb-data:
   driver: local
   driver_opts:
           device: /home/dgarizad/data/database
           o: bind
           type: none

networks:
  inceptionnet:
    driver: bridge
