
version: '3.8'

services:
 wordpress:
  build:
    context: ./requirements/wordpress
    dockerfile: Dockerfile
  image: wpimage:latest
  volumes:
    - ./requirements/public_html:/public_html
  restart: always
  expose:
    -  9000
  env_file: .env
  depends_on: 
    -  mariadb
  container_name: wpcontainer
  networks:
    -  inceptionnet


 mariadb:
    build:
      context: ./requirements/mariaDB/
      dockerfile: Dockerfile
    image: dbimage
    restart: always
    env_file: .env
    volumes:
      - mariadb-data:/var/lib/mysql
    container_name: dbcontainer
    networks:
      - inceptionnet

 nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: ngximage:latest
    restart: always
    env_file: .env
    volumes:
    - ./requirements/public_html:/public_html
    ports:
      - "443:443"
    depends_on:
      - wordpress
    container_name: ngxcontainer
    networks:
      - inceptionnet

volumes:
  # wpdata:
  mariadb-data:
   driver: local
   driver_opts:
           device: /home/dgarizad/data
           o: bind
           type: none

networks:
  inceptionnet:
    driver: bridge
