
version: '3.8'

services:
 wordpress:
  build:
    context: ./requirements/wordpress
    dockerfile: Dockerfile
  image: wpimage:latest
  restart: always
  env_file: .env
  ports:
    -  "8080:80"
  depends_on: 
    -  mariadb
  container_name: wpcontainer
  networks:
    -  inceptionnet


 mariadb:
    build:
      context: ./requirements/mariaDB/
      dockerfile: Dockerfile
    image: dbimage
    restart: always
    env_file: .env
    volumes:
      - mariadb-data:/var/lib/mysql
    container_name: dbcontainer
    networks:
      - inceptionnet

volumes:
  mariadb-data:
   driver: local
   driver_opts:
           device: /home/dgarizad/data
           o: bind
           type: none

networks:
  inceptionnet:
    driver: bridge
