# Use the Debian 11.8 base image
FROM debian:11.8

# Install PHP and required extensions
RUN apt-get update \
    && apt-get install -y php php-fpm php-mysql \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install WordPress
RUN apt-get update \
    && apt-get install -y wget \
    && wget https://wordpress.org/latest.tar.gz \
    && tar -xvzf latest.tar.gz \
    && rm latest.tar.gz \
    && mv wordpress /var/www/html \
    && chown -R www-data:www-data /var/www/html \
    && apt-get remove -y wget \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Set up PHP-FPM configuration
#COPY php-fpm.conf /etc/php/7.4/fpm/php-fpm.conf

# Expose port 9000 for PHP-FPM
EXPOSE 9000

# Start PHP-FPM
CMD ["php-fpm7.4", "-F"]

